#!/bin/bash

IPT="/sbin/iptables"

####USER CONFIG SECTION ###
IPfw="192.168.0.14"
IPhost="192.168.10.2"
intOut="em1"
intIn="p3p1"
TCPallow="6000,2000"
UDPallow="7000,3000"
ICMPallow="8"

#### END USER CONFIG SECTION ###

#Flush any existing rules
$IPT -X
$IPT -F

#Default policies
$IPT -P INPUT ACCEPT
$IPT -P FORWARD ACCEPT
$IPT -P OUTPUT ACCEPT


echo "New IPTABLES SET";


service iptables save
service iptables restart

iptables -L -v -x -n

